import { Inter } from "next/font/google";
import "./globals.css";
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/saga-blue/theme.css';
import "primereact/resources/primereact.min.css";
import NextAuthSessionProvider from "../utils/sessionProvider";
import { PrimeReactProvider } from 'primereact/api';
import DefaultLayout from "./components/Layout/DefaultLayout";
import { headers } from "next/headers";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const headersList = headers();
  const pathname = headersList.get('x-pathname') || '/'; // Default to '/' if header is not found
  const isAuthPage = pathname.includes('auth');

  console.log(`showing sidebar: ${isAuthPage ? 'no sidebar' : 'yes sidebar available'}`);
  const session = await auth();

  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <PrimeReactProvider>
          <body className={`${inter.className} bg-gray-100`}>
            {/* {!session ? (
              children
            ) : (
              <DefaultLayout>{children}</DefaultLayout>
            )} */}
            <DefaultLayout>{children}</DefaultLayout>
          </body>
        </PrimeReactProvider>
      </NextAuthSessionProvider>
    </html>
  );
}
